Update terms-of-use.md
OWND-Project/terms pull request #8
Opened 2023-12-18 03:20 UTC by sakamoto-datasign

first commit!

2023-12-18 09:24 UTC, DataSign-OTA requested changes
レビューしましたが、全体的にOWND Walletの特性を考えた記載に修正してほしいです。

2023-12-18 09:24 UTC, DataSign-OTA commented on wallet/terms-of-use.md
> +    4. 「事務局ウェブサイト」とは、そのドメインが[ownd-project.com](https://ownd-project.com)および、[datasign.jp](https://datasign.jp)である、事務局が運営するウェブサイト（理由の如何を問わず、事務局のウェブサイトのドメインまたは内容が変更された場合は、当該変更後のウェブサイトを含みます。）を意味します。
「事務局ウェブサイト」は必要無いと思いました。
定義からの削除と、参照しているところは削除して構いません。

2023-12-18 09:24 UTC, DataSign-OTA commented on wallet/terms-of-use.md
> +1. 事務局は、事務局が必要と認めた場合は、本規約を変更できるものとします。本契約を変更する場合、変更後の本規約の施行時期および内容を事務局ウェブサイト上での掲示その他の適切な方法により周知し、または利用者に通知します。但し、法令上利用者の同意が必要となる内容の変更の場合は、事務局所定の方法で利用者の同意を得るものとします。本規約の変更履歴はGitHubで公開しておりますので、こちらの[GitH
事務局ウェブサイトを　[本プロジェクトウェブサイト](https://ownd-project.com/)　に変更お願いします。

2023-12-18 09:24 UTC, DataSign-OTA commented on wallet/terms-of-use.md
> +1. 本アプリの利用を希望する者（以下「利用希望者」といいます。）は、本規約を遵守することに同意し、かつ事務局の定める一定の情報（以下「登録事項」といいます。）を事務局の定める方法で本アプリに提供することにより、本アプリの利用を開始することができます。
登録事項は特にないので削除して良いと思います。

2023-12-18 09:24 UTC, DataSign-OTA commented on wallet/terms-of-use.md
> +1. 本アプリの利用を希望する者（以下「利用希望者」といいます。）は、本規約を遵守することに同意し、かつ事務局の定める一定の情報（以下「登録事項」といいます。）を事務局の定める方法で本アプリに提供することにより、本アプリの利用を開始することができます。
同意をとっていないので、「本規約を遵守することに同意し」のところは言い方を考えたいです。

2023-12-18 09:24 UTC, DataSign-OTA commented on wallet/terms-of-use.md
> +1. 利用者は、事務局に提供した事項に変更があった場合、事務局の定める方法により当該変更事項を遅滞なく事務局に通知するものとします。
提供事項は特にないと思います。

2023-12-18 09:24 UTC, DataSign-OTA commented on wallet/terms-of-use.md
> +### 第9条　登録抹消等
登録しているわけでは無いので、書き方の修正が必要だと思います。

2023-12-18 09:24 UTC, DataSign-OTA commented on wallet/terms-of-use.md
> +1. 利用者は、事務局所定の手続の完了により、本アプリから退会し、自己の利用者としての登録を抹消することができます。
こちらも登録しているわけでは無く、入会しているわけではないので、退会というのも変だなと思います。

2023-12-18 09:24 UTC, DataSign-OTA commented on wallet/terms-of-use.md
> +2. 事務局が本アプリの提供を終了する場合、事務局は利用者に事前に通知するものとします。
事前に通知する方法が無いと思います。

2023-12-18 09:24 UTC, DataSign-OTA commented on wallet/terms-of-use.md
> +2. 事務局は、本アプリに関して利用者が被った損害につき、過去12ヶ月間に利用者が支払った対価の金額を超えて賠償する責任を負わないものとし、また、付随的損害、間接損害、特別損害、将来の損害および逸失利益にかかる損害については、賠償する責任を負わないものとします。
「払った対価の金額」が無い

2023-12-18 09:24 UTC, DataSign-OTA commented on wallet/terms-of-use.md
> +2. 事務局が登録事項に含まれるメールアドレスその他の連絡先に連絡または通知を行った場合、利用者は当該連絡または通知を受領したものとみなします。
登録事項が無いので、通知できない

2023-12-19 08:54 UTC, sakamoto-datasign commented on wallet/terms-of-use.md
> +    4. 「事務局ウェブサイト」とは、そのドメインが[ownd-project.com](https://ownd-project.com)および、[datasign.jp](https://datasign.jp)である、事務局が運営するウェブサイト（理由の如何を問わず、事務局のウェブサイトのドメインまたは内容が変更された場合は、当該変更後のウェブサイトを含みます。）を意味します。
定義を削除しました。

2023-12-19 08:54 UTC, sakamoto-datasign commented on wallet/terms-of-use.md
> +1. 事務局は、事務局が必要と認めた場合は、本規約を変更できるものとします。本契約を変更する場合、変更後の本規約の施行時期および内容を事務局ウェブサイト上での掲示その他の適切な方法により周知し、または利用者に通知します。但し、法令上利用者の同意が必要となる内容の変更の場合は、事務局所定の方法で利用者の同意を得るものとします。本規約の変更履歴はGitHubで公開しておりますので、こちらの[GitH
変更しました。

2023-12-19 08:56 UTC, sakamoto-datasign commented on wallet/terms-of-use.md
> +1. 本アプリの利用を希望する者（以下「利用希望者」といいます。）は、本規約を遵守することに同意し、かつ事務局の定める一定の情報（以下「登録事項」といいます。）を事務局の定める方法で本アプリに提供することにより、本アプリの利用を開始することができます。
該当文書を削除しました。

2023-12-19 08:57 UTC, sakamoto-datasign commented on wallet/terms-of-use.md
> +1. 本アプリの利用を希望する者（以下「利用希望者」といいます。）は、本規約を遵守することに同意し、かつ事務局の定める一定の情報（以下「登録事項」といいます。）を事務局の定める方法で本アプリに提供することにより、本アプリの利用を開始することができます。
「本規約を遵守し、本アプリの利用を開始することができます。」に変更しました。

2023-12-19 08:58 UTC, sakamoto-datasign commented on wallet/terms-of-use.md
> +1. 利用者は、事務局に提供した事項に変更があった場合、事務局の定める方法により当該変更事項を遅滞なく事務局に通知するものとします。
第4条を削除しました。

2023-12-19 09:00 UTC, sakamoto-datasign commented on wallet/terms-of-use.md
> +### 第9条　登録抹消等
「利用停止等」として内容を修正します。

2023-12-19 09:05 UTC, sakamoto-datasign commented on wallet/terms-of-use.md
> +2. 事務局が本アプリの提供を終了する場合、事務局は利用者に事前に通知するものとします。
「事務局はその旨を公表するものとします。」とします。

2023-12-19 09:07 UTC, sakamoto-datasign commented on wallet/terms-of-use.md
> +2. 事務局は、本アプリに関して利用者が被った損害につき、過去12ヶ月間に利用者が支払った対価の金額を超えて賠償する責任を負わないものとし、また、付随的損害、間接損害、特別損害、将来の損害および逸失利益にかかる損害については、賠償する責任を負わないものとします。
第2項を削除します。

2023-12-19 09:08 UTC, sakamoto-datasign commented on wallet/terms-of-use.md
> +2. 事務局が登録事項に含まれるメールアドレスその他の連絡先に連絡または通知を行った場合、利用者は当該連絡または通知を受領したものとみなします。
第16条は削除します。

2023-12-19 09:09 UTC, sakamoto-datasign commented
全体で「事務局ウェブサイト」「登録事項」の表記があるところを修正しました。

2023-12-19 09:14 UTC, sakamoto-datasign commented on wallet/terms-of-use.md
> +1. 利用者は、事務局所定の手続の完了により、本アプリから退会し、自己の利用者としての登録を抹消することができます。
第10条を削除します。

2023-12-20 01:00 UTC, DataSign-OTA commented on wallet/terms-of-use.md
> +2. 事務局は、本アプリに関して利用者が被った損害につき、過去12ヶ月間に利用者が支払った対価の金額を超えて賠償する責任を負わないものとし、また、付随的損害、間接損害、特別損害、将来の損害および逸失利益にかかる損害については、賠償する責任を負わないものとします。
2項すべて削除するのではなく、「過去12ヶ月間に利用者が支払った対価の金額を超えて」だけ削除したほうが良いと思います。

2023-12-20 04:18 UTC, sakamoto-datasign commented on wallet/terms-of-use.md
> +2. 事務局は、本アプリに関して利用者が被った損害につき、過去12ヶ月間に利用者が支払った対価の金額を超えて賠償する責任を負わないものとし、また、付随的損害、間接損害、特別損害、将来の損害および逸失利益にかかる損害については、賠償する責任を負わないものとします。
承知しました。第2項を戻して修正します。

2023-12-20 04:25 UTC, merged